version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: react-latest-playground:latest
    ports:
      - "3002:3002"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
